baseurl: https://math.blog.aurelienooms.be/
theme: prove
title: Aurélien's Math Notebook

taxonomies:
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - Calendar
  taxonomy:
    - HTML
    - RSS
    - Calendar
  section:
    - HTML
    - RSS
    - Calendar
  taxonomyTerm:
    - HTML
  page:
    - HTML
    - Calendar

params:
  organizer: '"Aurélien Ooms":mailto:info@math.blog.aurelienooms.be'
  hostname: math.blog.aurelienooms.be
  editURL: https://github.com/aureooms/math
