baseurl: https://math.blog.aurelienooms.be/
theme: prove
title: Aurélien's Math Notebook
buildFuture: true

permalinks:
  today: /:year/:month/:day/:title
  past: /:year/:month/:day/:title
  upcoming: /:year/:month/:day/:title

taxonomies:
  tag: tags
  author: authors

outputs:
  home:
    - HTML
    - RSS
    - Calendar
  section:
    - HTML
    - RSS
    - Calendar
  page:
    - HTML
    - Calendar
  taxonomy:
    - HTML
    - RSS
    - Calendar
  taxonomyTerm:
    - HTML

params:
  logo:
    src: https://cdn.jsdelivr.net/gh/aureooms-ulb/logo/files/ulb-logo-blue-square.svg
    alt: ULB
  organizer: 'CN="Aurélien Ooms":mailto:info@math.blog.aurelienooms.be'
  hostname: math.blog.aurelienooms.be
  editURL: https://github.com/aureooms/math
  nav:
    sections:
      - today
      - upcoming
      - past
    taxonomies:
      - tags
      - authors
  calendar:
    tzid: Europe/Brussels
    status:
      - CONFIRMED # Indicates event is definite.
      - TENTATIVE # Indicates event is tentative.
      - CANCELLED # Indicates event was cancelled.
    classification:
      - PUBLIC
      - PRIVATE
      - CONFIDENTIAL
